# Generated by Django 5.2 on 2025-06-25 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leilao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataInicio", models.DateField()),
                ("dataTermino", models.DateField()),
                ("horaInicio", models.TimeField()),
                ("horaTermino", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("endereco", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemLeilao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("lanceMinimo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("arrematado", models.BooleanField(default=False)),
                (
                    "leilao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itensLeilao",
                        to="leilao.leilao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valorLance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("horaLance", models.TimeField(auto_now_add=True)),
                (
                    "itemLeilao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lances",
                        to="leilao.itemleilao",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lances",
                        to="leilao.participante",
                    ),
                ),
            ],
        ),
    ]
