# Generated by Django 5.2 on 2025-06-05 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Raca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Macho"), ("F", "Fêmea")], max_length=1
                    ),
                ),
                ("cor", models.CharField(max_length=50)),
                ("dataNascimento", models.DateField()),
                ("descricao", models.TextField(blank=True, null=True)),
                ("disponivel", models.BooleanField(default=True)),
                (
                    "raca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gatos",
                        to="adocato.raca",
                    ),
                ),
            ],
        ),
    ]
