# Generated by Django 5.2 on 2025-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adocato", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gato",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="gatos/"),
        ),
        migrations.AlterField(
            model_name="gato",
            name="dataNascimento",
            field=models.DateField(verbose_name="Data de Nascimento"),
        ),
        migrations.AlterField(
            model_name="gato",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
    ]
