# Generated by Django 5.2 on 2025-07-03 12:44

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adocato", "0003_coordenador"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adotante",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                ("dataNascimento", models.DateField(verbose_name="Data de Nascimento")),
                (
                    "cpf",
                    models.CharField(max_length=11, unique=True, verbose_name="CPF"),
                ),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                ("estado", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "verbose_name": "Adotante",
                "verbose_name_plural": "Adotantes",
                "ordering": ["nome"],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="coordenador",
            options={
                "ordering": ["nome"],
                "verbose_name": "Coordenador",
                "verbose_name_plural": "Coordenadores",
            },
        ),
        migrations.AlterModelOptions(
            name="raca",
            options={
                "ordering": ["nome"],
                "verbose_name": "Raça",
                "verbose_name_plural": "Raças",
            },
        ),
        migrations.AlterField(
            model_name="coordenador",
            name="cpf",
            field=models.CharField(max_length=11, unique=True, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="gato",
            name="dataNascimento",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="gato",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataAvaliacao", models.DateTimeField(auto_now_add=True)),
                ("parecer", models.TextField(blank=True, null=True)),
                (
                    "coordenador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="adocato.coordenador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "ordering": ["-dataAvaliacao"],
            },
        ),
        migrations.CreateModel(
            name="Solicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataSolicitacao", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Em_Analise", "Em Análise"),
                            ("Aprovada", "Aprovada"),
                            ("Reprovada", "Reprovada"),
                            ("Em_Recurso", "Em Recurso"),
                        ],
                        default="Reprovada",
                        max_length=20,
                    ),
                ),
                (
                    "recurso",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo do Recurso"
                    ),
                ),
                (
                    "adotante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_adotante",
                        to="adocato.adotante",
                    ),
                ),
                (
                    "avaliadores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="avaliacoes_solicitadas",
                        through="adocato.Avaliacao",
                        to="adocato.coordenador",
                    ),
                ),
                (
                    "gato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_gato",
                        to="adocato.gato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação",
                "verbose_name_plural": "Solicitações",
                "ordering": ["-dataSolicitacao"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(upload_to="documentos/", verbose_name="Arquivo"),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "enviado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="adocato.solicitacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["solicitacao__adotante__nome"],
            },
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="solicitacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="adocato.solicitacao",
            ),
        ),
    ]
