# Generated by Django 5.2 on 2025-07-15 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adocato", "0004_adotante_alter_coordenador_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gato",
            options={
                "ordering": ["nome"],
                "permissions": [("pode_deletar_gato", "Pode deletar gato")],
                "verbose_name": "Gato",
                "verbose_name_plural": "Gatos",
            },
        ),
    ]
