# Generated by Django 5.2 on 2025-07-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adocato", "0005_alter_gato_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("Em_Edicao", "Em Edição"),
                    ("Em_Analise", "Em Análise"),
                    ("Aprovada", "Aprovada"),
                    ("Reprovada", "Reprovada"),
                    ("Em_Recurso", "Em Recurso"),
                ],
                default="Em_Edicao",
                max_length=20,
            ),
        ),
    ]
